name: GAN

seed: 999
device: cuda

data_dir: /home/user/PyTorch-Lightning-GAN/GAN/celeba 
batch_size: 128
zdim: 100
img_size: 64
img_ch: 3
epochs: 50
workers: 4
# number of iterations of the discriminator per generator iteration
d_iter_per_g: 1

# learning rate for generator (g) and discriminator (d)
lr:
  g: 2.0e-4
  d: 2.0e-4

g_norm_type: BatchNorm2d
d_norm_type: BatchNorm2d
g_final_activation: "tanh"
d_final_activation: "sigmoid"



# save generated images every save_img_freq epochs
save_image_freq: 50
# save model every save_model_freq epochs
save_model_freq: 50
# saved weights directory
weights_dir: chkpt
# directory where a sample grid of images will be saved
images_dir: images
comet_workspace: wgan
comet_project: wgan-gp
resume: True
# directory where samples from generate_images.py will be saved
samples_dir: samples
# number of epoch to run to generate samples
num_sample_epochs: 20


